sudo: required
services:
  - docker

before_install:
  - docker build -t mathieucolin/docker-training -f Dockerfile.dev .

script:
  - docker run -e CI=true mathieucolin/docker-training npm run test

deploy:
  provider: elasticbenstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-700545129804"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
